field: 33421b8c-6785-4293-9138-04092ff71a0a # Page Block Content
fieldLayouts:
  480fc2c6-bff8-4688-9936-8063121b40ee:
    tabs:
      -
        elementCondition: null
        elements:
          -
            elementCondition: null
            fieldUid: dfd441da-d2f6-47d6-8bc0-732e455675fc # Heading
            instructions: null
            label: null
            required: true
            tip: null
            type: craft\fieldlayoutelements\CustomField
            uid: 7bd924fc-40d5-4b23-8e12-421e2f1cf09c
            userCondition: null
            warning: null
            width: 100
          -
            elementCondition: null
            fieldUid: 98b33985-738a-42d4-ba69-715d4cfec476 # Padding
            instructions: null
            label: null
            required: true
            tip: null
            type: craft\fieldlayoutelements\CustomField
            uid: d27e0167-4ba3-4007-85e8-925d59216d34
            userCondition: null
            warning: null
            width: 100
          -
            elementCondition: null
            fieldUid: 38c04d3c-ffb9-4998-b4e8-4fdef2b45140 # Background Color
            instructions: null
            label: null
            required: true
            tip: null
            type: craft\fieldlayoutelements\CustomField
            uid: 2ad762cf-7c7f-4617-aa48-b7c54457b61d
            userCondition: null
            warning: null
            width: 100
          -
            elementCondition: null
            fieldUid: c6430037-f0dc-4409-9d97-8a43f574bc35 # Text Color
            instructions: null
            label: null
            required: true
            tip: null
            type: craft\fieldlayoutelements\CustomField
            uid: 04e9d1ff-17e4-4472-856c-439f17659d91
            userCondition: null
            warning: null
            width: 100
          -
            elementCondition: null
            fieldUid: 3c728594-6779-4645-a109-eae666db19bc # Alignment
            instructions: null
            label: null
            required: false
            tip: null
            type: craft\fieldlayoutelements\CustomField
            uid: 7dd80e80-32ca-4b95-a48e-a9e9fdec44c1
            userCondition: null
            warning: null
            width: 100
          -
            elementCondition: null
            fieldUid: e0658619-c52b-4227-8563-6418d290d76d # Full Width
            instructions: null
            label: null
            required: false
            tip: null
            type: craft\fieldlayoutelements\CustomField
            uid: 720041ec-cd2a-4fd7-bfae-269504eeaaba
            userCondition: null
            warning: null
            width: 100
        name: Content
        uid: 978ba47a-b040-4503-8134-9be217d3a708
        userCondition: null
fields:
  3c728594-6779-4645-a109-eae666db19bc: # Alignment
    columnSuffix: urdyqfkp
    contentColumnType: string(6)
    fieldGroup: null
    handle: alignment
    instructions: null
    name: Alignment
    searchable: false
    settings:
      columnType: null
      options:
        -
          __assoc__:
            -
              - label
              - Left
            -
              - value
              - left
            -
              - default
              - ''
        -
          __assoc__:
            -
              - label
              - Center
            -
              - value
              - center
            -
              - default
              - ''
        -
          __assoc__:
            -
              - label
              - Right
            -
              - value
              - right
            -
              - default
              - ''
    translationKeyFormat: null
    translationMethod: none
    type: craft\fields\Dropdown
  38c04d3c-ffb9-4998-b4e8-4fdef2b45140: # Background Color
    columnSuffix: yvdgqzyf
    contentColumnType: string(9)
    fieldGroup: null
    handle: backgroundColor
    instructions: null
    name: 'Background Color'
    searchable: false
    settings:
      columnType: null
      options:
        -
          __assoc__:
            -
              - label
              - White
            -
              - value
              - white
            -
              - default
              - '1'
        -
          __assoc__:
            -
              - label
              - Primary
            -
              - value
              - primary
            -
              - default
              - ''
        -
          __assoc__:
            -
              - label
              - Secondary
            -
              - value
              - secondary
            -
              - default
              - ''
        -
          __assoc__:
            -
              - label
              - 'Light Gray'
            -
              - value
              - gray-100
            -
              - default
              - ''
        -
          __assoc__:
            -
              - label
              - 'Dark Gray'
            -
              - value
              - gray-300
            -
              - default
              - ''
    translationKeyFormat: null
    translationMethod: none
    type: craft\fields\Dropdown
  98b33985-738a-42d4-ba69-715d4cfec476: # Padding
    columnSuffix: nqxbrfrv
    contentColumnType: string(9)
    fieldGroup: null
    handle: padding
    instructions: null
    name: Padding
    searchable: false
    settings:
      columnType: null
      options:
        -
          __assoc__:
            -
              - label
              - 'Top & Bottom'
            -
              - value
              - topBottom
            -
              - default
              - '1'
        -
          __assoc__:
            -
              - label
              - Top
            -
              - value
              - top
            -
              - default
              - ''
        -
          __assoc__:
            -
              - label
              - Bottom
            -
              - value
              - bottom
            -
              - default
              - ''
        -
          __assoc__:
            -
              - label
              - None
            -
              - value
              - none
            -
              - default
              - ''
    translationKeyFormat: null
    translationMethod: none
    type: craft\fields\Dropdown
  c6430037-f0dc-4409-9d97-8a43f574bc35: # Text Color
    columnSuffix: fdckyxjt
    contentColumnType: string(5)
    fieldGroup: null
    handle: textColor
    instructions: null
    name: 'Text Color'
    searchable: false
    settings:
      columnType: null
      options:
        -
          __assoc__:
            -
              - label
              - Dark
            -
              - value
              - dark
            -
              - default
              - ''
        -
          __assoc__:
            -
              - label
              - Light
            -
              - value
              - light
            -
              - default
              - ''
    translationKeyFormat: null
    translationMethod: none
    type: craft\fields\Dropdown
  dfd441da-d2f6-47d6-8bc0-732e455675fc: # Heading
    columnSuffix: vvbphmkk
    contentColumnType: text
    fieldGroup: null
    handle: heading
    instructions: null
    name: Heading
    searchable: false
    settings:
      availableTransforms: ''
      availableVolumes: '*'
      columnType: text
      configSelectionMode: choose
      defaultTransform: ''
      manualConfig: ''
      purifierConfig: null
      purifyHtml: true
      redactorConfig: null
      removeEmptyTags: false
      removeInlineStyles: false
      removeNbsp: false
      showHtmlButtonForNonAdmins: false
      showUnpermittedFiles: false
      showUnpermittedVolumes: false
      uiMode: enlarged
    translationKeyFormat: null
    translationMethod: none
    type: craft\redactor\Field
  e0658619-c52b-4227-8563-6418d290d76d: # Full Width
    columnSuffix: ikxkllww
    contentColumnType: boolean
    fieldGroup: null
    handle: fullWidth
    instructions: null
    name: 'Full Width'
    searchable: false
    settings:
      default: false
      offLabel: null
      onLabel: null
    translationKeyFormat: null
    translationMethod: none
    type: craft\fields\Lightswitch
handle: heading
name: Heading
sortOrder: 1
