fieldLayouts:
  05074e93-a159-4473-85bf-b0aea2b225e8:
    tabs:
      -
        elementCondition: null
        elements:
          -
            autocapitalize: true
            autocomplete: false
            autocorrect: true
            class: null
            disabled: false
            elementCondition: null
            id: null
            instructions: null
            label: null
            max: null
            min: null
            name: null
            orientation: null
            placeholder: null
            readonly: false
            requirable: false
            size: null
            step: null
            tip: null
            title: null
            type: craft\fieldlayoutelements\entries\EntryTitleField
            uid: 03f088c7-ed9e-465f-a3a5-b7860f092383
            userCondition: null
            warning: null
            width: 100
          -
            elementCondition: null
            fieldUid: 049868b7-e248-42c1-ae96-5d568bb2675b # Case Study Title
            instructions: null
            label: null
            required: false
            tip: null
            type: craft\fieldlayoutelements\CustomField
            uid: beced9fe-b067-4ab8-b4e4-1ac946c72ea2
            userCondition: null
            warning: null
            width: 100
          -
            elementCondition: null
            fieldUid: 652648f3-da7a-40b1-ac2f-9f33cce4c3f0 # Case Study Content
            instructions: null
            label: null
            required: false
            tip: null
            type: craft\fieldlayoutelements\CustomField
            uid: a5aa5920-b2b7-4c11-abcc-8c2ba231b48f
            userCondition: null
            warning: null
            width: 100
          -
            elementCondition: null
            fieldUid: 33421b8c-6785-4293-9138-04092ff71a0a # Page Block Content
            instructions: null
            label: null
            required: false
            tip: null
            type: craft\fieldlayoutelements\CustomField
            uid: ce5b7a03-a1dc-4f26-934c-3133984e1b5f
            userCondition: null
            warning: null
            width: 100
        name: Content
        uid: 07fd1740-fc70-46f9-91f3-0d254879598e
        userCondition: null
      -
        elementCondition: null
        elements:
          -
            elementCondition: null
            fieldUid: b09a3af7-b1af-4d1b-abbb-48e31b4e941e # Case Study Images
            instructions: null
            label: null
            required: false
            tip: null
            type: craft\fieldlayoutelements\CustomField
            uid: bfa54b8a-f53c-43d5-9c42-a860a0d2ff9b
            userCondition: null
            warning: null
            width: 100
          -
            elementCondition: null
            fieldUid: c18846da-80b6-4931-bec1-ddb09c469730 # Case Study Logo
            instructions: null
            label: null
            required: false
            tip: null
            type: craft\fieldlayoutelements\CustomField
            uid: 360dfebe-3249-4717-bf6a-9a0f53a4bac1
            userCondition: null
            warning: null
            width: 100
          -
            elementCondition: null
            fieldUid: da359cb4-78db-467d-b169-a51e0e0b5db1 # Case Study Meta
            instructions: null
            label: null
            required: false
            tip: null
            type: craft\fieldlayoutelements\CustomField
            uid: 4332e5a6-1c15-4f70-8c60-29657db51666
            userCondition: null
            warning: null
            width: 100
        name: Info
        uid: 8620f5c4-f6be-43c8-8f95-be209750b9c8
        userCondition: null
      -
        elementCondition: null
        elements:
          -
            elementCondition: null
            fieldUid: aec1a5d9-1184-4df7-b3c5-636cb53a7e22 # Case Study Testimonial
            instructions: null
            label: null
            required: false
            tip: null
            type: craft\fieldlayoutelements\CustomField
            uid: 99e6e846-54ac-4dd4-a330-738be7626a0d
            userCondition: null
            warning: null
            width: 100
        name: Testimonial
        uid: 5be27ac6-fb32-42de-a431-02ccf5588c4d
        userCondition: null
handle: default
hasTitleField: true
name: Default
section: fa480103-052f-4a4f-b1e3-c945261051bc # Case Studies
showStatusField: true
slugTranslationKeyFormat: null
slugTranslationMethod: site
sortOrder: 1
titleFormat: null
titleTranslationKeyFormat: null
titleTranslationMethod: site
