fieldLayouts:
  cdc92256-669b-46d2-aefd-7264e9e0e074:
    tabs:
      -
        elementCondition: null
        elements:
          -
            autocapitalize: true
            autocomplete: false
            autocorrect: true
            class: null
            disabled: false
            elementCondition: null
            id: null
            instructions: null
            label: null
            max: null
            min: null
            name: null
            orientation: null
            placeholder: null
            readonly: false
            requirable: false
            size: null
            step: null
            tip: null
            title: null
            type: craft\fieldlayoutelements\entries\EntryTitleField
            uid: cdacd75d-5442-4eb2-82ae-4f9162f9ce46
            userCondition: null
            warning: null
            width: 100
          -
            elementCondition: null
            fieldUid: 33421b8c-6785-4293-9138-04092ff71a0a # Page Block Content
            instructions: null
            label: null
            required: false
            tip: null
            type: craft\fieldlayoutelements\CustomField
            uid: f48eaf6d-fb42-4623-9b26-4b03bf35b7cd
            userCondition: null
            warning: null
            width: 100
        name: Content
        uid: 557208aa-bf9e-4655-ae4c-1f933fa5a5fe
        userCondition: null
handle: homepage
hasTitleField: false
name: Homepage
section: 3140ea00-e81b-4a46-a027-be95ae54214a # Homepage
showStatusField: true
slugTranslationKeyFormat: null
slugTranslationMethod: site
sortOrder: 1
titleFormat: '{section.name|raw}'
titleTranslationKeyFormat: null
titleTranslationMethod: site
