defaultPlacement: end
enableVersioning: true
handle: page
name: Page
propagationMethod: all
siteSettings:
  4930992f-525c-475e-9723-4617531c9573: # Volaris
    enabledByDefault: true
    hasUrls: true
    template: _pages/entry.twig
    uriFormat: '{slug}'
structure:
  maxLevels: null
  uid: db015462-2512-4557-838d-797fda7c719c
type: structure
